---
# Source: dagster-user-deployments/templates/configmap-env-shared.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-user-deployments-user-deployments-shared-env
  labels:
    app: dagster-user-deployments
    chart: dagster-user-deployments-0.15.0
    release: dagster-user-deployments
    heritage: Helm
data:
  
  
  
  DAGSTER_HOME: "/opt/dagster/dagster_home"
  DAGSTER_K8S_PG_PASSWORD_SECRET: "dagster-postgresql-secret"
  DAGSTER_K8S_INSTANCE_CONFIG_MAP: "dagster-user-deployments-instance"
  DAGSTER_K8S_PIPELINE_RUN_NAMESPACE: "default"
  DAGSTER_K8S_PIPELINE_RUN_ENV_CONFIGMAP: "dagster-user-deployments-pipeline-env"
