---
# Source: dagster-user-deployments/templates/deployment-user.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-user-deployments-user-code
  labels:
    helm.sh/chart: dagster-user-deployments-0.15.0
    app.kubernetes.io/name: dagster-user-deployments
    app.kubernetes.io/instance: dagster-user-deployments
    app.kubernetes.io/version: "0.15.0"
    app.kubernetes.io/managed-by: Helm
    component: user-deployments
    deployment: user-code
  annotations: 
    {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dagster-user-deployments
      app.kubernetes.io/instance: dagster-user-deployments
      component: user-deployments
      deployment: user-code
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dagster-user-deployments
        app.kubernetes.io/instance: dagster-user-deployments
        component: user-deployments
        deployment: user-code
      annotations:
        checksum/dagster-user-deployment: 18dee5047f31e72e305a8ae1c4ea64a8a46421bd7cf4eabf4dc2239d9303ca69
    spec:
      imagePullSecrets: 
        []
      serviceAccountName: dagster-user-deployments-user-deployments
      securityContext: 
        {}
      containers:
        - name: dagster-user-deployments
          securityContext: 
            {}
          imagePullPolicy: Always
          image: "docker.io/dagster/user-code-example:0.15.0"
          command: ["dagster"]
          args: ["api", "grpc", "-h", "0.0.0.0", "-p", "3030", "-f","/example_project/example_repo/repo.py"]
          env:
            - name: DAGSTER_CURRENT_IMAGE
              value: "docker.io/dagster/user-code-example:0.15.0"
            - name: DAGSTER_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dagster-postgresql-secret
                  key: postgresql-password
            # uses the auto_envvar_prefix of the dagster cli to set the --container-context arg
            # on 'dagster api grpc'
            - name: DAGSTER_CLI_API_GRPC_CONTAINER_CONTEXT
              value: "{\"k8s\":{\"env_config_maps\":[\"dagster-user-deployments-user-code-user-env\"],\"image_pull_policy\":\"Always\",\"namespace\":\"default\",\"service_account_name\":\"dagster-user-deployments-user-deployments\"}}"
          envFrom:
            - configMapRef:
                name: dagster-user-deployments-user-deployments-shared-env
            - configMapRef:
                name: dagster-user-deployments-user-code-user-env
            - secretRef:
                name: dagster-celery-config-secret
                optional: true
          resources: 
            {}
          readinessProbe:
            exec:
              command: ["dagster", "api", "grpc-health-check", "-p", "3030"]
            periodSeconds:
              20
            timeoutSeconds:
              3
            successThreshold:
              1
            failureThreshold:
              3
      nodeSelector: 
        {}
      affinity: 
        {}
      tolerations:
        []
