---
# Source: dagster-user-deployments/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dagster-user-deployments-user-deployments
  labels: 
    helm.sh/chart: dagster-user-deployments-0.15.0
    app.kubernetes.io/name: dagster-user-deployments
    app.kubernetes.io/instance: dagster-user-deployments
    app.kubernetes.io/version: "0.15.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
