---
# Source: dagster/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: dagster-postgresql
  labels:
    app: postgresql
    chart: postgresql-8.1.0
    release: "dagster"
    heritage: "Helm"
type: Opaque
data:
  postgresql-password: "dGVzdA=="
