---
# Source: dagster/charts/postgresql/templates/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: dagster-postgresql-headless
  labels:
    app: postgresql
    chart: postgresql-8.1.0
    release: "dagster"
    heritage: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: "dagster"
