---
# Source: dagster/templates/configmap-instance.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-instance
  labels:
    app: dagster
    chart: dagster-0.15.0
    release: dagster
    heritage: Helm
data:
  dagster.yaml: |
    scheduler:      
      module: dagster.core.scheduler
      class: DagsterDaemonScheduler

    schedule_storage:
      module: dagster_postgres.schedule_storage
      class: PostgresScheduleStorage
      config:        
        postgres_db:
          username: test
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: dagster-postgresql
          db_name: test
          port: 5432
          params:
            {}

    run_launcher:      
      module: dagster_k8s
      class: K8sRunLauncher
      config:
        load_incluster_config: true
        job_namespace: default
        image_pull_policy: Always
        service_account_name: dagster
        dagster_home: "/opt/dagster/dagster_home"
        instance_config_map: "dagster-instance"
        postgres_password_secret: "dagster-postgresql-secret"

    run_storage:
      module: dagster_postgres.run_storage
      class: PostgresRunStorage
      config:        
        postgres_db:
          username: test
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: dagster-postgresql
          db_name: test
          port: 5432
          params:
            {}

    event_log_storage:
      module: dagster_postgres.event_log
      class: PostgresEventLogStorage
      config:        
        postgres_db:
          username: test
          password:
            env: DAGSTER_PG_PASSWORD
          hostname: dagster-postgresql
          db_name: test
          port: 5432
          params:
            {}
    compute_logs:      
      module: dagster.core.storage.noop_compute_log_manager
      class: NoOpComputeLogManager

    telemetry:
      enabled: true
