---
# Source: dagster/templates/service-dagit.yaml
apiVersion: v1
kind: Service
metadata:
  name: dagster-dagit
  labels:
    helm.sh/chart: dagster-0.15.0
    app.kubernetes.io/name: dagster
    app.kubernetes.io/instance: dagster
    app.kubernetes.io/version: "0.15.0"
    app.kubernetes.io/managed-by: Helm
    component: dagit
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dagster
    app.kubernetes.io/instance: dagster
    component: dagit
