---
# Source: dagster-user-deployments/templates/configmap-env-shared.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-user-deployments-user-deployments-shared-env
data:
  DAGSTER_K8S_PIPELINE_RUN_NAMESPACE: "dagster-staging"
